# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vexillum < Formula
  desc "CLI orchestrator for code agents"
  homepage "https://github.com/isaias-alt/vexillum"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_darwin_amd64.tar.gz"
      sha256 "af819822b31bb97a95f2fa0e1cd2725683ea34a534786806464290706341585c"

      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_darwin_arm64.tar.gz"
      sha256 "4d9716442e011c5925b0cc542528df5817ad7f606abcece4d970987180235596"

      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_linux_amd64.tar.gz"
      sha256 "26c754d965754e1af24256e213d7ff1027c4e62cb87003d0c582075401cd4427"
      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_linux_arm64.tar.gz"
      sha256 "f4902f2a422c08ebd3594bd0df1914e94c26e1997fbb9a1325e6b2c79dd7d7c2"
      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
  end

  def caveats
    <<~EOS
      vx needs Claude Code (logged in) and herdr installed.
      Run `vx init` inside a git repository to set it up.
      Then run `vx doctor` to check your environment.
      Docs: https://vx.lucasco.dev
    EOS
  end

  test do
    system "#{bin}/vx", "--version"
  end
end
