# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VexillumRehearsal < Formula
  desc "CLI orchestrator for code agents"
  homepage "https://github.com/isaias-alt/vexillum-rehearsal"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isaias-alt/vexillum-rehearsal/releases/download/v0.1.0/vexillum_0.1.0_darwin_amd64.tar.gz"
      sha256 "d09412ad8f81041251843d943e3e4dcc461c2a82f36fe5033e29cdef68dc2d35"

      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isaias-alt/vexillum-rehearsal/releases/download/v0.1.0/vexillum_0.1.0_darwin_arm64.tar.gz"
      sha256 "d4d8c2075a0251de876cf0428e300dbbc8356c8aa0e29475482dd0734dcf6bc1"

      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum-rehearsal/releases/download/v0.1.0/vexillum_0.1.0_linux_amd64.tar.gz"
      sha256 "491788cc6cb558fa354f2baaa11ef6fe1c3fd1338c6a4b55313475f67cc6bc4b"
      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum-rehearsal/releases/download/v0.1.0/vexillum_0.1.0_linux_arm64.tar.gz"
      sha256 "8cbb0f3ad54dbb7d4cc56fe6a76ea0777db397ae0f0534df1e5659d4b3c64ca3"
      define_method(:install) do
        bin.install "vx"
        doc.install "LICENSE", "THIRD-PARTY-NOTICES.md"
      end
    end
  end

  def caveats
    <<~EOS
      vx needs Claude Code (logged in) and herdr installed.
      Run `vx init` inside a git repository to set it up.
      Then run `vx doctor` to check your environment.
      Docs: https://vx.lucasco.dev
    EOS
  end

  test do
    system "#{bin}/vx", "--version"
  end
end
