# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vexillum < Formula
  desc "CLI orchestrator for code agents"
  homepage "https://github.com/isaias-alt/vexillum"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_darwin_amd64.tar.gz"
      sha256 "bdd08d1810637af5c3942b570aea59316ee88438e3c2449292adffd72f40a6df"

      define_method(:install) do
        bin.install "vexillum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_darwin_arm64.tar.gz"
      sha256 "156c17c16a60fc8605fc63786bfda7f8ae636f4aad856bac0a1d8cbb4cd1c000"

      define_method(:install) do
        bin.install "vexillum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_linux_amd64.tar.gz"
      sha256 "d7424ba383d7681748f3ca039987e61a1c09e194f792a3cabbbe6882f5781eb3"
      define_method(:install) do
        bin.install "vexillum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isaias-alt/vexillum/releases/download/v0.1.0/vexillum_0.1.0_linux_arm64.tar.gz"
      sha256 "618fa907ae35221561030691dbecb37e3aed23266af5a623fcfa9d93801976f9"
      define_method(:install) do
        bin.install "vexillum"
      end
    end
  end

  test do
    system "#{bin}/vexillum", "--version"
  end
end
